######################################################################
# Automatically generated by qmake (3.0) ? 12? 19 14:26:21 2019
######################################################################

TEMPLATE = app
TARGET = pro10
INCLUDEPATH += .

 
QT += widgets

# Input
HEADERS += ButtonWindow.h
SOURCES += ButtonWindow.cpp
